<!-- FORMULAIRE POUR MODIFIER LA REALISATION -->
<h2>Modification d'une réalisation</h2>

<form enctype="multipart/form-data" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=update" method="POST">

    <input type="hidden" name="id" value="<?= intval($_GET['id']); ?>" />
    
    <fieldset>
        
        <legend>Modifier la réalisation</legend>
                
        <div>
            <label for="name_realisation">Nom de la réalisation : </label>
            <input type="text" id="name_realisation" name="name_realisation" value="<?= htmlspecialchars($tplVars['form']['name']);?>">
        </div>

        <div>
            <label for="theme">Thème de la réalisation: </label>
            <div>
                <select class="form-control" id="theme" name="theme">		
                    
                    <!-- boucler sur les rayons -->
					<?php foreach($tplVars['themes'] as $item): ?>
						<option value="<?= intval($item['Id']);?>"<?php echo (intval($tplVars['form']['Themes_Id']) == $item['Id']) ? ' selected' : '';?>><?= htmlspecialchars($item['name']);?></option>
					<?php endforeach; ?>
                    
				</select>
            </div>
        </div>
                
        <button class="btn">Modifier la réalisation</button>
    
    </fieldset>
    </form>