<!-- LISTE DES REALISATIONS -->
<section>
    
    <h2>Gestion des réalisations</h2>
    <hr>
            
    <div class="new">
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=newForm">Ajouter une réalisations</a>
    </div>
    
    <table id="table-backend">
        <thead>
            <tr>
                <th>Noms de la réalisations</th>
                <th>Thèmes</th>
                <th>Actions</th>
            </tr>   
        </thead>
        <tbody>
            <!-- BOUCLE SUR LES REALISATIONS -->
            <?php foreach($tplVars['list'] as $item): ?>
                <tr>
                
				    <td><?= htmlspecialchars($item['name']); ?></td>
                    <td><?= htmlspecialchars($item['Themes']); ?></td>
				    <td>
                        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=editForm&id=<?= intval($item['Id']);?>" class="modif">Modifier</a>
                        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=delete&id=<?= intval($item['Id']);?>" class="suppr">Supprimer</a>
                    </td>
                
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</section>    