<!-- FORMULAIRE POUR AJOUTER UNE REALISATION -->
<h2>Ajouter une réalisation</h2>

<form enctype="multipart/form-data" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=create" method="POST">

    <fieldset>

        <legend>Nouvelle réalisation</legend>

        <div>
            <label for="name_realisation">Nom de la réalisation : </label>
            <input type="text" id="name_realisation" name="name_realisation" value="">
        </div>
    
        <div>
            <label for="photo_principale" data-browse="Parcourir">Photo de la réalisation <small>au format png</small>: </label>
            <input type="file" id="photo_principale" name="photo_principale">
        </div>

        <div>
            <label for="theme">Thème de la réalisation : </label>
            <div>
                <select class="form-control" id="theme" name="theme">
					<option value="0">Choisir un thème ...</option>

						<!-- boucler sur les réalisations -->
						<?php foreach($tplVars['themes'] as $item):?>
							<option value="<?= intval($item['Id']);?>"><?= htmlspecialchars($item['name']);?></option>
						<?php endforeach; ?>
				</select>
            </div>
        </div>

        <button class="validate">Ajouter la réalisation</button>

    </fieldset>
</form>