<section>
    <h2>Ajouter un Administrateur</h2>
    <form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin&task=addAdmin" method="POST">
        <div>
            <label for="nom">Nom :</label>
            <input type="text" id="nom" name="nom" required>
        </div>
        <div>
            <label for="prenom">Prénom :</label>
            <input type="text" id="prenom" name="prenom" required>
        </div>
        <div>
            <label for="mail">Email :</label>
            <input type="email" id="mail" name="mail" required>
        </div>
        <div>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div>
            <button type="submit" class="validate">Ajouter l'administrateur</button>
        </div>
    </form>
</section>