<!-- ACCUEIL DE LA PARTIE ADMINISTRATION / DASHBOARD -->
<h2>Tableau de bord</h2>

<section id="menu">

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Realisations&task=index">
            <h3>Gestion des Réalisations</h3>
            <p>Ajouter, Modifier, Supprimer une réalisation</p>
        </a>
    </article>

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Themes&task=index">
            <h3>Gestion des Thèmes</h3>
            <p>Ajouter, Supprimer un thème</p>
        </a>
    </article>

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\Contact&task=index">
            <h3>Gestion des Mails</h3>
            <p>Visualiser les mails</p>
        </a>
    </article>

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin&task=listUsers">
            <h3>Gestion des Adminstrateurs/Utilistateurs</h3>
        </a>
    </article>

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin&task=addAdminForm">
            <h3>Ajout d'un administrateur</h3>
        </a>
    </article>

    <article>
        <a href="<?= $tplVars['WWW_URL']; ?>" target="_blank">
            <h3>Acceder au site </h3>
        </a>
    </article>

</section>